#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 17 23:47:40 2018

@author: jinrui06
"""

import sklearn
import numpy as np
import pandas as pd
from sklearn import cross_validation as cv
from sklearn.metrics.pairwise import pairwise_distances
from sklearn.metrics import mean_squared_error
from math import sqrt
import tensorflow as tf 
from tensorflow import feature_column
#读取用户对item打分到pd
user_item_pd = pd.read_csv('../data/ml-100k/u.data',sep='\t',names=['user_id', 'item_id', 'rating', 'timestamp'])

#读取用户特征到pd
user_feature_pd = pd.read_csv('../data/ml-100k/u.user',sep='\|',names=['user_id', 'age', 'gender', 'occupation','zipcode'])

#读取item特征到pd
item_feature_pd = pd.read_csv('../data/ml-100k/u.item',sep='\|',names=['mvid', 'mvtitle', 'releasedate', 'vdreleasedate','imdburl','unknow','action','adventure',
                                                                      'animation','children','comedy','crime','Documentary','Drama',
                                                                       'Fantasy','film_noir','horror','musical','mystery','romance','sci_fi','thriller','war','western'])
item_features = {}
imp_map = {'jan':'06','jul':'07'}
def changeImp(x):

    imps = x.split('-')
    imps.reverse()

item_feature_pd = item_feature_pd.drop(['mvtitle','imdburl'],axis=1)
for col in item_feature_pd.columns:
    #print(item_feature_pd[col])
    item_features[col] = [[val] for val in item_feature_pd[col]]


print(item_features)